### ISSUE TITLE
Ability to exclude symbols/namespaces by regex match

### ISSUE THREAD

**Issue by jtbandes** [hdoc/hdoc#16]
Feature request: I would like to be able to exclude certain symbols, or symbols under certain namespaces, from the documentation and search index.

This is one of the only remaining things I have to maintain in a patch: https://github.com/foxglove/mcap/blob/a85bd00295255b134f3083efbc5d2274294a83df/cpp/hdoc.patch

It would be great to specify an exclusion pattern in the config file, preferably using regular expressions for maximum flexibility. As an example:

```toml
[ignore]
ignore_records = "^(.*::)?internal::.*$"
ignore_functions = "^(.*::)?internal::.*$"
```
