### ISSUE TITLE
hdoc doesn't detect my comments

### ISSUE THREAD

**Issue by strager** [hdoc/hdoc#28]
I'm trying hdoc, and it doesn't seem to show my class comments in the generated documentation.

Code:
https://github.com/quick-lint/quick-lint-js/blob/079240a6bc89b7386e5e092b67442a85e8d49b6e/src/quick-lint-js/fe/parse.h#L83-L85

hdoc output:
<img width="1068" alt="Screen Shot 2022-10-01 at 3 08 23 PM" src="https://user-images.githubusercontent.com/48666/193430124-472a8055-c991-4ae8-a6b2-fae17cf28f80.png">

---

It doesn't seem to work with member functions either:
https://github.com/quick-lint/quick-lint-js/blob/079240a6bc89b7386e5e092b67442a85e8d49b6e/src/quick-lint-js/fe/parse.h#L103-L111
<img width="1052" alt="Screen Shot 2022-10-01 at 3 09 09 PM" src="https://user-images.githubusercontent.com/48666/193430143-08a1bef4-024b-484f-9f91-80a4b4e56540.png">

or anything else I've looked at.

---

Here's my `.hdoc.toml`:
```toml
[project]
name = "quick-lint-js"
version = "2.9.0"

git_repo_url = "https://github.com/quick-lint/quick-lint-js/blob/master/"

[paths]
compile_commands = "build/compile_commands.json"
output_dir = "build/hdoc"
```
